language: node_js
node_js:
  - stable
cache:
  npm: true
  directories:
    - dref/dns/node_modules
    - dref/api/node_modules
    - dref/scripts/node_modules
env:
  - TEST_DIR=dref/dns
script: cd $TEST_DIR && npm install && npm test && codecov
